### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Tooconfident** [miller3000/prj-rev-bwfs-dasmoto#4]
Grade: Meets Expectations

Overall your project is well structured and the code looks great! You show a solid understanding of div containers and different ways to use semantic class and id names. The suggestions I detailed along the other issues are just ideas going forward that will help you on bigger projects and helping your code, especially your CSS stay DRY(Don't Repeat Yourself). You accomplish this already overall so great job!

This is a nice resource focusing on DRY css, if you are interested:

http://vanseodesign.com/css/dry-principles/

**Comment by miller3000** [comment]
Thanks for your useful comments!
